= takctl

== About

Takctl is a tool to interact with TAK clients and servers from the terminal.
It is developed using https://quarkus.io[Quarkus], a modern Java framework.

The project is currently under development and working toward an initial release.
We are looking for contributors- if you would like to participate in the project, please open an issue or pull request.

== Usage

The `takctl` CLI is invoked with a hierarchy of commands to perform various functions.
For complete usage information, run `takctl --help`.

== Building

Takctl is intended to be run as a native binary rather than the JVM.
(JVM startup time would be unacceptable for an interactive tool.) Therefore, it is recommended to build a native executable with GraalVM:

[source,shell]
----
quarkus build --native
----

The build will output the `takctl` binary to the `build` directory.

Native compilation can be too slow for practical use in the development cycle.
For takctl development, you should prefer using Quarkus development mode, described next.

== Dev mode

Quarkus dev mode is invoked by running `quarkus dev`.
Dev mode allows the application to be quickly re-run as code is modified by pressing the <space> key.
Command-line options may be modified within the session by pressing the 'e' key.

