= takctl

== About

Takctl is a tool to interact with TAK clients and servers from the terminal.
It is developed using https://quarkus.io[Quarkus], a modern Java framework.

The project is currently under development and working toward an initial release.
We are looking for contributors- if you would like to participate in the project, please open an issue or pull request.

== Usage

The `takctl` CLI is invoked with a hierarchy of commands to perform various functions.
For complete usage information, run `takctl --help`.

== Building

Takctl is intended to be run as a native binary rather than the JVM, mainly to provide a fast startup time.
Therefore, it is recommended to build a native executable with GraalVM:

[source,shell]
----
quarkus build --native
----

The build will output the `takctl` binary to the `build` directory.

Native compilation can be too slow for practical use in the development cycle.
For takctl development, you should prefer using Quarkus development mode.

Development mode is invoked by running `quarkus dev`.
This mode allows the application to be quickly re-run as code is modified by pressing the <space> key.
Command-line options may be modified within the session by pressing the 'e' key.

== Envisioned Use Cases

Some use case ideas to inspire future development:

- Manage TAK Server configuration from the CLI rather than a web app (feeds, QoS, everything else)
- Add or remove users, generate client certs
- View TAK Server health and metrics
- Send messages to connected client(s), interactive chat


